# Generated by Django 4.1.3 on 2022-12-02 11:38

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Auth', models.CharField(max_length=255)),
                ('subject', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=225)),
                ('time', models.DateTimeField(auto_now=True)),
                ('Content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('slug', models.CharField(max_length=130)),
            ],
        ),
    ]
