# Generated by Django 4.1.3 on 2022-12-03 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_dbms_digitalelectronics_maths_oop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='Content',
        ),
        migrations.RemoveField(
            model_name='course',
            name='title',
        ),
    ]
