# Generated by Django 4.1.3 on 2022-12-01 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_blog_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='about',
            field=models.TextField(max_length=200),
        ),
    ]
